name: Redis Keep Alive

on:
  schedule:
    - cron: "0 0 */5 * *" # every 5 days at midnight UTC
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Redis
        run: |
          curl -X POST "$UPSTASH_REDIS_REST_URL/ping" \
          -H "Authorization: Bearer $UPSTASH_REDIS_REST_TOKEN"
        env:
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
